[build]
rustflags = ["--cfg", "tokio_unstable"]

[alias]
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
todoers = ["run", "--release", "--package", "todoers", "--"]
server = ["run", "--package", "todoers-server", "--"]
